- hosts: gitlab 
  gather_facts: true
  become:
    true
  become_method:
    sudo
  become_user:
    root
  remote_user:
    smarzhic
  roles:
   - Gitlab

  environment:
     http_proxy: http://zhukops.ru:8118
     https_proxy: http://zhukops.ru:8118
  