- hosts: MySQL app gitlab runner monitoring
  gather_facts: true
  become:
    true
  become_method:
    sudo
  become_user:
    root
  remote_user:
    smarzhic
  roles:
   - Install-node-exporter

  environment:
     http_proxy: http://zhukops.ru:8118
     https_proxy: http://zhukops.ru:8118




scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: "prometheus"

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "prometheus_node"
    scrape_interval: 5s
    static_configs:
      - targets: ["localhost:9100"]

  - job_name: "db02_node"
    scrape_interval: 5s
    static_configs:
      - targets: ["db02.zhukops.ru:9100"]

  - job_name: "db01_node"
    scrape_interval: 5s
    static_configs:
      - targets: ["db01.zhukops.ru:9100"]

  - job_name: "runner_node"
    scrape_interval: 5s
    static_configs:
      - targets: ["runner.zhukops.ru:9100"]

# - job_name: "zhukops_node"
#   scrape_interval: 5s
#   static_configs:
#      - targets: ["zhukops.ru:9100"]

#  - job_name: "gitlab_node"
#    scrape_interval: 5s
#    static_configs:
#     - targets: ["gitlab.zhukops.ru:9100"]

#  - job_name: "app_node"
#    scrape_interval: 5s
#    static_config:
#     - targets: ["app.zhukops.ru:9100"]
